#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require(__DIR__ . '/vendor/autoload.php');

(Dotenv\Dotenv::createUnsafeImmutable(__DIR__ . '/'))->safeLoad();

defined('YII_DEBUG') or define('YII_DEBUG', getenv('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));


require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/src/LNPay.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/main.php'),
    require(__DIR__ . '/config/main-local.php'),
    require(__DIR__ . '/config/console.php'),
    require(__DIR__ . '/config/console-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
