<?php


return
    [
        [
            'id'=>5,
            'user_id'=>147,
            'domain_name'=>'lnpay.local',
            'port'=>80,
            'display_name'=>'local_1',
            'use_https'=>null,
            'status_type_id'=>50,
            'ssl_info'=>'',
            'use_hsts'=>'',
            'upgrade_insecure'=>'',
            'external_hash'=>'cdom_123',
            'data'=>''
        ],
        [
            'id'=>6,
            'user_id'=>69,
            'domain_name'=>'lnpay.local',
            'port'=>80,
            'display_name'=>'lnod_carol',
            'external_hash'=>'cdom_444',
            'use_https'=>null,
            'status_type_id'=>50,
            'ssl_info'=>'',
            'use_hsts'=>'',
            'upgrade_insecure'=>'',
            'data'=>''
        ]
    ];
