<?php


return
    [
        [
            'id'=>5,
            'user_id'=>147,
            'domain_name'=>'lnpay.local',
            'port'=>80,
            'display_name'=>'lnod_carol',
            'use_https'=>'wal_LWAcZwCeDsezSfFe',
            'status_type_id'=>50,
            'ssl_info'=>'',
            'use_hsts'=>'',
            'upgrade_insecure'=>'',
            'data'=>''
        ],
        [
            'id'=>6,
            'user_id'=>69,
            'domain_name'=>'lnpay.local',
            'port'=>80,
            'display_name'=>'lnod_carol',
            'use_https'=>'wal_LWAcZwCeDsezSfFe',
            'status_type_id'=>50,
            'ssl_info'=>'',
            'use_hsts'=>'',
            'upgrade_insecure'=>'',
            'data'=>''
        ]
    ];
