<?php
return [
    'user1' => [
        'id'=>147,
        'api_parent_id'=> null,
        'org_id'=>10,
        'username' => 'bandit',
        'auth_key' => 'K3nF70it7tzNsHddEiq0BZ0i-OU8S3xV',
        'mfa_secret_key'=>null,
        'password_hash' => '$2y$13$9LZ5X4420SffJCGCtohnHu2Rc.MSF2y7V9imlHq2M0OwqGa6PBRoa',
        'password_reset_token' => NULL,
        'email'=>'strosin.vernice@jerde.com',
        'email_verify'=>0,
        'external_hash'=>'usr_XIXkpKKKSJmDqW',
        'status'=>10,
        'created_at' => time(),
        'updated_at' => time(),
        'balance'=>null,
        'tz'=>'',
        'json_data'=>null
    ],
    'user2' => [
        'id'=>69,
        'api_parent_id'=> null,
        'api_version'=>null,
        'username' => 'jsonTester',
        'auth_key' => 'JsonTesterAuthKey',
        'mfa_secret_key'=>null,
        'password_hash' => '$2y$13$WSyE5hHsG1rWN2jV8LRHzubilrCLI5Ev/iK0r3jRuwQEs2ldRu.a2',
        'password_reset_token' => NULL,
        'email'=>'jsonTest@gmail.com',
        'email_verify'=>0,
        'external_hash'=>'usr_XXXXJSONTESTER',
        'status'=>10,
        'created_at' => time(),
        'updated_at' => time(),
        'balance'=>null,
        'tz'=>'',
        'json_data'=>['lnurl_ott'=>'tester-ott']
    ],
];