<?php


return
[
    [
        'id'=>5,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'test carol',
        'balance'=>117,
        'ln_node_id'=>'lnod_carol',
        'external_hash'=>'wal_LWAcZwCeDsezSfFe',
        'json_data'=>"{\"ott\": {\"YVI6TiqQuq75MG9fUmxdHuwHtzmC9\": \"YVI6TiqQuq75MG9fUmxdHuwHtzmC9\", \"bBZyx1Ti2FEZm4picXIWj2OJ01n6Ktf\": \"bBZyx1Ti2FEZm4picXIWj2OJ01n6Ktf\"}}",
        'status_type_id'=>200,
    ],
    [
        'id'=>6,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'wallet 6 bob',
        'balance'=>100,
        'ln_node_id'=>'lnod_bob',
        'external_hash'=>'LWAcasdfOt6i93WFh',
        'json_data'=>"{\"ott\": {\"YVI6TiqQuq75MG9fUmxdHuwHtzmC9\": \"YVI6TiqQuq75MG9fUmxdHuwHtzmC9\", \"bBZyx1Ti2FEZm4picXIWj2OJ01n6Ktf\": \"bBZyx1Ti2FEZm4picXIWj2OJ01n6Ktf\"}}",
        'status_type_id'=>200,
    ],
    [
        'id'=>7,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'wallet 7 alice',
        'balance'=>100,
        'ln_node_id'=>'lnod_alice',
        'external_hash'=>'wal_KkMmfMmsksss',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>8,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'test carol transactions',
        'balance'=>117,
        'ln_node_id'=>'lnod_carol',
        'external_hash'=>'wal_testCarolTransactions',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>9,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'carol transfer',
        'balance'=>0,
        'ln_node_id'=>'lnod_carol',
        'external_hash'=>'wal_carolTransfer1',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>10,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'alice lnurl withdraw',
        'balance'=>0,
        'ln_node_id'=>'lnod_alice',
        'external_hash'=>'wal_aliceLnurlWithdraw',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>11,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'alice lnurl pay',
        'balance'=>0,
        'ln_node_id'=>'lnod_alice',
        'external_hash'=>'wal_aliceLnurlPay',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>12,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'rollup compress test wallet',
        'balance'=>0,
        'ln_node_id'=>'lnod_alice',
        'external_hash'=>'wal_aliceRollUpCompress',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
    [
        'id'=>13,
        'created_at'=>1576066208,
        'updated_at'=>1576150264,
        'user_id'=>147,
        'user_label'=>'carol transfer 2',
        'balance'=>20,
        'ln_node_id'=>'lnod_carol',
        'external_hash'=>'wal_carolTransfer2',
        'json_data'=>"",
        'status_type_id'=>200,
    ],
];
